If:                               # Apply this config conditionally
  PathMatch: .*\.*                # to all headers and c files...
CompileFlags:                     # Tweak the parse settings
  Add: [-include postgres.h, -include relcache.h]
